name: Node

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Cache Node Modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }} 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, update, and outdated
      run: |
        npm ci
        npm run build --if-present
        npm update
        npm outdated
      env:
        CI: true
        
